# Setup
title:               Apmox
tagline:             'A Github Page'
description:         ''
url:                 http://apmox.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

